# Generated by Django 3.1.7 on 2021-06-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=500, unique=True)),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('post_code', models.CharField(blank=True, max_length=300, null=True)),
                ('units', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('payment_plan', models.CharField(choices=[('Monthly', 'Monthly'), ('Per Semester', 'Per Semester')], max_length=100)),
                ('default_house_type', models.CharField(choices=[('Single', 'Single'), ('Bed-Sitter', 'Bed-Sitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Three Bedroom', 'Three Bedroom'), ('Four Bedroom', 'Four Bedroom')], max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('agency_commission', models.FloatField()),
                ('auto_house_id', models.BooleanField(default=True)),
                ('apartment_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('air_conditioners', models.BooleanField(default=False)),
                ('car_parking', models.BooleanField(default=False)),
                ('laundry_room', models.BooleanField(default=False)),
                ('heaters', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('commission_date', models.DateTimeField()),
                ('decommission_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caretaker',
                'verbose_name_plural': 'Caretakers',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('house_type', models.CharField(choices=[('Single', 'Single'), ('Bed-Sitter', 'Bed-Sitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Three Bedroom', 'Three Bedroom'), ('Four Bedroom', 'Four Bedroom')], max_length=200)),
                ('rent', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('arrears', models.IntegerField(default=0)),
                ('vacant', models.BooleanField(default=True)),
                ('house_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaidRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('date_paid', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.house')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start_date', models.DateField(auto_now_add=True)),
                ('lease_end_date', models.DateField()),
                ('lease_documents', models.FileField(blank=True, null=True, upload_to='')),
                ('current_status', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.apartment')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.caretaker'),
        ),
    ]
