# Generated by Django 3.1.7 on 2021-07-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0002_lease_running_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='running_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
