# Generated by Django 3.1.7 on 2021-07-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0003_auto_20210705_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidrent',
            name='apartment',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Tenants.apartment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_incurred', models.FloatField(default=0)),
                ('fully_paid', models.BooleanField(default=False)),
                ('date_generated', models.DateField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.apartment')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tenants.house')),
            ],
        ),
    ]
