# Generated by Django 3.1.7 on 2021-07-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0004_auto_20210705_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Tenants.tenant'),
            preserve_default=False,
        ),
    ]
