# Generated by Django 3.1.7 on 2021-07-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0005_invoice_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='Tenants.lease'),
            preserve_default=False,
        ),
    ]
