# Generated by Django 3.1.7 on 2021-07-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0006_invoice_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
