# Generated by Django 3.1.7 on 2021-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0007_auto_20210707_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_due',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
