# Generated by Django 3.1.7 on 2021-07-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0008_invoice_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='previous_over_dues',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
