# Generated by Django 3.1.7 on 2021-07-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0009_invoice_previous_over_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidrent',
            name='payment_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidrent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tenants.tenant'),
        ),
    ]
