# Generated by Django 3.1.7 on 2021-07-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0010_auto_20210709_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidrent',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tenants.lease'),
        ),
    ]
