# Generated by Django 3.1.7 on 2021-07-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0011_paidrent_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='commission_date',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='decommission_date',
        ),
    ]
