# Generated by Django 3.1.7 on 2021-07-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0012_auto_20210727_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Tenants.caretaker'),
        ),
    ]
